// Matriz de interpretación por ítem · BARNA
// Extraída de la hoja 'Matriz de Intepretación' del archivo de respuestas.
// Para cada ítem: interpretación de niveles 1-2 (low), 3 (mid), 4-5 (high),
// la señal diagnóstica que mide y los perfiles que alimenta.

window.MATRIX = (function () {
  const dimTitles = {
    "D1": "Relación con el error y la incertidumbre",
    "D2": "Poder, jerarquía y origen de las ideas",
    "D3": "Cultura de datos vs. intuición e improvisación",
    "D4": "Relación con el tiempo y la velocidad",
    "D5": "Identidad organizacional y apertura al cambio",
    "D6": "Capacidades digitales y disposición hacia la IA",
    "D7": "Colaboración, silos y capital social interno",
    "D8": "Liderazgo y modelaje de comportamientos innovadores"
  };

  const items = [
    {
      code: "D1.1",
      dim: "D1",
      text: "Cuando un proyecto falla en mi empresa, el líder que lo propuso asume responsabilidades públicamente y continúa siendo considerado para roles importantes.",
      low: "El error tiende a penalizar trayectorias o cerrar oportunidades futuras.",
      mid: "La tolerancia al error existe de forma parcial o depende del caso.",
      high: "El error puede asumirse públicamente sin castigo desproporcionado ni pérdida injusta de oportunidades.",
      signal: "Seguridad psicológica frente al error",
    },
    {
      code: "D1.2",
      dim: "D1",
      text: "En mi empresa se documentan formalmente los aprendizajes obtenidos de proyectos que no funcionaron como se esperaba.",
      low: "No existe aprendizaje formal del fracaso; los errores se pierden o se silencian.",
      mid: "El aprendizaje se registra de forma ocasional o informal.",
      high: "Los proyectos que no funcionan generan aprendizajes documentados y aprovechables.",
      signal: "Aprendizaje organizacional del fracaso",
    },
    {
      code: "D1.3",
      dim: "D1",
      text: "Cuando ocurre un error, en mi empresa se analiza primero cómo mejorar procesos, decisiones o formas de trabajo antes que señalar culpables.",
      low: "Predomina la búsqueda de culpables sobre la mejora de procesos.",
      mid: "Conviven prácticas de mejora con prácticas de señalamiento.",
      high: "El error se analiza como oportunidad para mejorar procesos, decisiones o formas de trabajo.",
      signal: "Cultura no punitiva",
    },
    {
      code: "D1.4",
      dim: "D1",
      text: "Puedo proponer una idea arriesgada sin preocuparme de que, si no funciona, eso afecte cómo me ven en la empresa.",
      low: "Las personas evitan ideas arriesgadas por temor a deteriorar su reputación interna.",
      mid: "La disposición a proponer ideas riesgosas depende del área, líder o contexto.",
      high: "Existe seguridad suficiente para proponer ideas con incertidumbre sin temor reputacional excesivo.",
      signal: "Seguridad para experimentar",
    },
    {
      code: "D1.5",
      dim: "D1",
      text: "En mi empresa, los proyectos que no logran los resultados esperados se reportan con transparencia a la alta dirección, incluyendo sus causas, aprendizajes y elementos de mejora.",
      low: "Los resultados fallidos tienden a maquillarse, ocultarse o comunicarse parcialmente.",
      mid: "La transparencia sobre resultados fallidos es irregular o depende del nivel de confianza.",
      high: "Los resultados no esperados se comunican con transparencia y se conectan con aprendizajes concretos.",
      signal: "Transparencia frente al fracaso",
    },
    {
      code: "D1.6",
      dim: "D1",
      text: "En mi empresa existe un espacio formal o informal donde se analiza por qué algo no salió bien.",
      low: "No hay espacios reconocibles para revisar fallos y aprender de ellos.",
      mid: "Existen conversaciones esporádicas, pero no una práctica consistente de revisión.",
      high: "Hay espacios formales o informales que permiten analizar fallos y convertirlos en mejora.",
      signal: "Espacios de aprendizaje del error",
    },
    {
      code: "D2.1",
      dim: "D2",
      text: "En mi empresa, las ideas de mejora o innovación pueden surgir de distintos niveles de la organización, no solo de la alta dirección o de los dueños.",
      low: "Las ideas están concentradas principalmente en la alta dirección o propiedad.",
      mid: "Existen algunas ideas desde otros niveles, pero con alcance limitado.",
      high: "Las ideas fluyen desde distintos niveles y no dependen solo de la alta dirección.",
      signal: "Origen distribuido de las ideas",
    },
    {
      code: "D2.2",
      dim: "D2",
      text: "Cuando un empleado de niveles medios o bajos propone algo nuevo, recibe retroalimentación concreta, honesta y respetuosa.",
      low: "Las propuestas desde niveles medios u operativos reciben poca respuesta o respuestas vagas.",
      mid: "La retroalimentación existe, pero no siempre es concreta, honesta o respetuosa.",
      high: "Las propuestas reciben retroalimentación útil, clara y respetuosa, sin importar el nivel jerárquico.",
      signal: "Calidad de la retroalimentación a ideas ascendentes",
    },
    {
      code: "D2.3",
      dim: "D2",
      text: "En mi empresa, las ideas se evalúan principalmente por su calidad, viabilidad y aporte de valor, más que por el nivel jerárquico de quien las propone.",
      low: "El nivel jerárquico pesa más que la calidad o valor de la idea.",
      mid: "La evaluación combina mérito de la idea con influencia jerárquica.",
      high: "Las ideas se valoran por su calidad, viabilidad y aporte, no por el cargo de quien las propone.",
      signal: "Meritocracia de ideas",
    },
    {
      code: "D2.4",
      dim: "D2",
      text: "En mi empresa existen mecanismos concretos (buzones, reuniones, plataformas) para que cualquier empleado proponga cambios.",
      low: "No existen mecanismos claros para canalizar propuestas de mejora.",
      mid: "Existen mecanismos, pero se usan poco o no generan seguimiento claro.",
      high: "Hay canales concretos y utilizables para que cualquier empleado proponga cambios.",
      signal: "Canales formales o informales de participación",
    },
    {
      code: "D2.5",
      dim: "D2",
      text: "Los empleados más jóvenes tienen oportunidades reales de que sus ideas sean escuchadas y consideradas, independientemente de su edad o antigüedad en la empresa.",
      low: "La edad o antigüedad limita la escucha de ideas de empleados jóvenes.",
      mid: "La escucha a empleados jóvenes existe, pero con barreras o condiciones.",
      high: "Las ideas de empleados jóvenes se escuchan y consideran por su valor, no por su edad o antigüedad.",
      signal: "Apertura generacional a las ideas",
    },
    {
      code: "D2.6",
      dim: "D2",
      text: "Una idea nueva puede avanzar en la organización cuando demuestra valor, aunque inicialmente no provenga de la máxima autoridad.",
      low: "Las ideas dependen fuertemente del visto bueno inicial de la máxima autoridad.",
      mid: "Algunas ideas avanzan por mérito, pero la autorización superior sigue siendo decisiva.",
      high: "Las ideas pueden avanzar por su valor, aunque no nazcan desde arriba.",
      signal: "Descentralización de la aprobación de ideas",
    },
    {
      code: "D2.7",
      dim: "D2",
      text: "Las mujeres tienen oportunidades reales de que sus ideas sean escuchadas y consideradas en igualdad de condiciones que los hombres.",
      low: "La escucha y consideración de ideas presenta barreras de género.",
      mid: "La igualdad de escucha existe en algunos espacios, pero no de manera consistente.",
      high: "Las ideas de las mujeres se escuchan y consideran en igualdad de condiciones.",
      signal: "Equidad de género en la escucha de ideas",
      note: "Se corrigió redacción final para no mezclar género con antigüedad o edad.",
    },
    {
      code: "D3.1",
      dim: "D3",
      text: "En mi empresa se toman decisiones importantes basadas en datos concretos antes que en la intuición del directivo.",
      low: "Las decisiones importantes dependen principalmente de intuición o criterio personal sin evidencia suficiente.",
      mid: "Los datos se consideran, pero no siempre pesan más que la intuición directiva.",
      high: "Las decisiones importantes se fundamentan prioritariamente en datos concretos.",
      signal: "Orientación a evidencia en decisiones relevantes",
    },
    {
      code: "D3.2",
      dim: "D3",
      text: "Cuando los datos contradicen una decisión que ya se había tomado, generalmente se revisa esa decisión.",
      low: "Los datos rara vez modifican decisiones ya tomadas.",
      mid: "Las decisiones se revisan a veces, según la presión o el actor involucrado.",
      high: "Los datos tienen capacidad real de corregir o ajustar decisiones previas.",
      signal: "Apertura a revisar decisiones con evidencia",
    },
    {
      code: "D3.3",
      dim: "D3",
      text: "Los reportes e indicadores disponibles se utilizan de forma práctica para orientar las decisiones del día a día, incluso si no muestran los resultados esperados.",
      low: "Los reportes existen, pero no orientan la operación cotidiana ni se usan cuando muestran resultados incómodos.",
      mid: "Los indicadores se usan de manera parcial o irregular.",
      high: "Los reportes e indicadores guían decisiones diarias, incluso cuando revelan desviaciones.",
      signal: "Uso práctico de indicadores",
    },
    {
      code: "D3.4",
      dim: "D3",
      text: "En mi empresa, antes de tomar decisiones relevantes, se revisan los datos en lugar de hacer caso únicamente a la opinión, el 'olfato' o la intuición de las personas con más experiencia acumulada.",
      low: "La experiencia o intuición de figuras influyentes prevalece sobre los datos.",
      mid: "Se revisan datos, pero la experiencia acumulada todavía domina muchas decisiones.",
      high: "Los datos se revisan antes de decidir y contrastan la intuición o experiencia acumulada.",
      signal: "Contraste entre intuición y evidencia",
    },
    {
      code: "D3.5",
      dim: "D3",
      text: "Los equipos tienen acceso real y oportuno a los datos que necesitan para tomar decisiones en su área.",
      low: "Los equipos no cuentan con datos suficientes, oportunos o accesibles para decidir.",
      mid: "El acceso a datos existe, pero es incompleto, tardío o desigual entre áreas.",
      high: "Los equipos acceden oportunamente a los datos necesarios para decidir en su ámbito.",
      signal: "Acceso a información para decidir",
    },
    {
      code: "D3.6",
      dim: "D3",
      text: "En mi empresa se mide sistemáticamente si los cambios implementados produjeron los resultados esperados.",
      low: "Los cambios se implementan sin medición sistemática de resultados.",
      mid: "Algunos cambios se miden, pero no existe una práctica consistente de evaluación.",
      high: "La organización mide de forma sistemática los resultados de los cambios implementados.",
      signal: "Evaluación de impacto de los cambios",
    },
    {
      code: "D4.1",
      dim: "D4",
      text: "En mi empresa existe tiempo protegido (reuniones, sprints, proyectos piloto) dedicado exclusivamente a experimentar con ideas nuevas.",
      low: "No hay tiempo protegido para experimentar o explorar mejoras.",
      mid: "Existe algo de tiempo para innovar, pero es vulnerable a la presión operativa.",
      high: "La organización reserva tiempo concreto para experimentar con ideas nuevas.",
      signal: "Tiempo protegido para innovación",
    },
    {
      code: "D4.2",
      dim: "D4",
      text: "En mi empresa, las urgencias del día a día se gestionan sin impedir de forma recurrente que los equipos trabajen en proyectos de mejora o innovación.",
      low: "La urgencia operativa bloquea regularmente los proyectos de mejora e innovación.",
      mid: "La urgencia interfiere con frecuencia, aunque algunas iniciativas logran avanzar.",
      high: "Las urgencias se gestionan sin desplazar recurrentemente la mejora o innovación.",
      signal: "Gestión de la urgencia operativa",
    },
    {
      code: "D4.3",
      dim: "D4",
      text: "En mi empresa, los recursos —tiempo, dinero y personas— se asignan considerando tanto las necesidades urgentes como las iniciativas importantes para el futuro.",
      low: "Los recursos se consumen casi totalmente en lo urgente y dejan poco espacio al futuro.",
      mid: "La asignación equilibra parcialmente urgencias e iniciativas de futuro.",
      high: "La organización asigna recursos equilibrando operación presente e iniciativas futuras.",
      signal: "Balance entre corto plazo y futuro estratégico",
    },
    {
      code: "D4.4",
      dim: "D4",
      text: "La planificación anual de mi empresa es un ejercicio real que guía las decisiones durante el año.",
      low: "La planificación anual es formal o decorativa y guía poco las decisiones.",
      mid: "La planificación orienta algunas decisiones, pero se debilita frente a la operación diaria.",
      high: "La planificación anual guía decisiones y prioridades durante el año.",
      signal: "Uso real de la planificación",
    },
    {
      code: "D4.5",
      dim: "D4",
      text: "Las iniciativas de largo plazo cuentan con seguimiento y continuidad, aun cuando surgen prioridades operativas.",
      low: "Las iniciativas de largo plazo se retrasan o cancelan con facilidad ante prioridades operativas.",
      mid: "El seguimiento existe, pero la continuidad depende de la presión operativa.",
      high: "Las iniciativas de largo plazo se sostienen con seguimiento aun frente a urgencias operativas.",
      signal: "Continuidad de iniciativas estratégicas",
    },
    {
      code: "D4.6",
      dim: "D4",
      text: "Los líderes protegen activamente el tiempo de sus equipos para que puedan trabajar en proyectos de mejora.",
      low: "Los líderes no protegen tiempo para mejora; la operación absorbe al equipo.",
      mid: "Algunos líderes protegen tiempo, pero no es una práctica extendida.",
      high: "Los líderes protegen activamente tiempo para mejora e innovación.",
      signal: "Protección directiva del tiempo para mejorar",
    },
    {
      code: "D5.1",
      dim: "D5",
      text: "En mi empresa se escucha con genuina apertura a quien propone hacer las cosas de manera diferente.",
      low: "Las propuestas diferentes suelen ser ignoradas, minimizadas o recibidas con resistencia.",
      mid: "Hay apertura parcial, dependiente del área, tema o persona que propone.",
      high: "La organización escucha con apertura genuina propuestas para hacer las cosas de otra manera.",
      signal: "Apertura a formas distintas de trabajar",
    },
    {
      code: "D5.2",
      dim: "D5",
      text: "En mi empresa, la historia y la tradición se utilizan como fuente de aprendizaje para impulsar mejoras, no como argumento para evitar cambios necesarios.",
      low: "La tradición se usa para justificar la permanencia de prácticas que deberían revisarse.",
      mid: "La historia inspira algunas mejoras, pero también limita cambios en ciertos temas.",
      high: "La trayectoria se usa como aprendizaje y base para mejorar, no como freno al cambio.",
      signal: "Uso adaptativo de la tradición",
    },
    {
      code: "D5.3",
      dim: "D5",
      text: "Los empleados que cuestionan procesos establecidos son vistos como posibles agentes de mejora, en lugar de problemáticos, siempre que presenten argumentos o propuestas constructivas.",
      low: "Quienes cuestionan procesos tienden a ser vistos como problemáticos.",
      mid: "El cuestionamiento se acepta solo en ciertos casos o si proviene de ciertas personas.",
      high: "El cuestionamiento constructivo se interpreta como aporte a la mejora.",
      signal: "Aceptación del cuestionamiento constructivo",
    },
    {
      code: "D5.4",
      dim: "D5",
      text: "Mi empresa ha cambiado procesos o prácticas que siempre habíamos hecho igual, cuando encontramos mejores formas.",
      low: "La organización mantiene prácticas históricas aun cuando hay mejores alternativas.",
      mid: "Algunos procesos cambian, pero otros permanecen por inercia.",
      high: "La empresa modifica prácticas históricas cuando encuentra mejores formas de trabajar.",
      signal: "Capacidad de abandonar inercias",
    },
    {
      code: "D5.5",
      dim: "D5",
      text: "En las decisiones estratégicas, la evidencia de que algo puede mejorar pesa más que la costumbre de hacerlo 'como siempre'.",
      low: "La costumbre pesa más que la evidencia de mejora.",
      mid: "La evidencia influye, pero la costumbre todavía condiciona decisiones estratégicas.",
      high: "La evidencia de mejora pesa más que la costumbre en decisiones estratégicas.",
      signal: "Evidencia frente a inercia cultural",
    },
    {
      code: "D5.6",
      dim: "D5",
      text: "El orgullo por la trayectoria de la empresa convive con una disposición real a revisar, actualizar o transformar prácticas cuando es necesario.",
      low: "El orgullo por la trayectoria limita la revisión de prácticas actuales.",
      mid: "Hay orgullo institucional y disposición parcial a revisar ciertas prácticas.",
      high: "La identidad histórica convive con apertura real a revisar y transformar prácticas.",
      signal: "Identidad organizacional adaptativa",
    },
    {
      code: "D6.1",
      dim: "D6",
      text: "La mayoría de los empleados de mi empresa se siente cómoda usando herramientas digitales en su trabajo diario.",
      low: "Predomina incomodidad o baja competencia en el uso cotidiano de herramientas digitales.",
      mid: "La comodidad digital es desigual entre áreas, generaciones o niveles.",
      high: "La mayoría usa herramientas digitales con comodidad en el trabajo diario.",
      signal: "Competencia digital cotidiana",
    },
    {
      code: "D6.2",
      dim: "D6",
      text: "En mi empresa, las preocupaciones sobre la posible sustitución, reducción o transformación de puestos de trabajo por la automatización o la inteligencia artificial se conversan de forma abierta, transparente y responsable.",
      low: "Los temores sobre desplazamiento laboral por IA o automatización no se conversan o se manejan con opacidad.",
      mid: "El tema se conversa parcialmente, pero con poca claridad o seguimiento.",
      high: "La organización conversa de forma abierta y responsable los posibles impactos laborales de la IA y automatización.",
      signal: "Gestión transparente del temor al desplazamiento laboral",
    },
    {
      code: "D6.3",
      dim: "D6",
      text: "Los líderes de mi empresa comprenden suficientemente las herramientas de inteligencia artificial disponibles para el negocio.",
      low: "Los líderes muestran comprensión limitada de herramientas de IA aplicables al negocio.",
      mid: "La comprensión directiva de IA es parcial o concentrada en pocas personas.",
      high: "Los líderes comprenden herramientas de IA y sus posibles usos para el negocio.",
      signal: "Comprensión directiva de IA",
    },
    {
      code: "D6.4",
      dim: "D6",
      text: "Si mañana se introdujera una herramienta de IA en mi empresa, la reacción predominante sería de curiosidad y apertura.",
      low: "La reacción esperada sería rechazo, miedo, indiferencia o resistencia.",
      mid: "La reacción sería mixta: curiosidad en algunos grupos y resistencia en otros.",
      high: "La reacción predominante sería curiosidad, apertura y disposición a aprender.",
      signal: "Apertura psicológica hacia IA",
    },
    {
      code: "D6.5",
      dim: "D6",
      text: "En mi empresa se toma en cuenta si los empleados considerarían inapropiado o incómodo automatizar ciertas tareas, aunque sea técnicamente posible hacerlo.",
      low: "La automatización se evalúa solo por factibilidad técnica, sin considerar incomodidad o sensibilidad humana.",
      mid: "Las preocupaciones sobre automatización se consideran en algunos casos, pero no de forma sistemática.",
      high: "La organización considera la percepción de los empleados antes de automatizar tareas sensibles.",
      signal: "Adopción responsable de automatización",
    },
    {
      code: "D6.6",
      dim: "D6",
      text: "La infraestructura tecnológica de mi empresa (internet, dispositivos, software) permite trabajar de forma eficiente.",
      low: "La infraestructura tecnológica limita la eficiencia del trabajo.",
      mid: "La infraestructura permite operar, pero con brechas o fallas recurrentes.",
      high: "La infraestructura tecnológica facilita un trabajo eficiente.",
      signal: "Base tecnológica disponible",
    },
    {
      code: "D6.7",
      dim: "D6",
      text: "Antes de adoptar una nueva tecnología, en mi empresa se pregunta cómo afectará a los puestos de trabajo actuales.",
      low: "La adopción tecnológica se decide sin evaluar impactos en puestos actuales.",
      mid: "El impacto laboral se considera de forma parcial o tardía.",
      high: "Antes de adoptar tecnología, se analiza cómo afectará a los puestos de trabajo actuales.",
      signal: "Evaluación de impacto laboral de la tecnología",
    },
    {
      code: "D7.1",
      dim: "D7",
      text: "En mi empresa, la innovación es responsabilidad compartida por todos los departamentos, no solo del área de tecnología o marketing.",
      low: "La innovación se percibe como responsabilidad de un área específica.",
      mid: "La responsabilidad por innovar es compartida solo en algunos equipos o proyectos.",
      high: "La innovación se entiende como responsabilidad compartida por todas las áreas.",
      signal: "Responsabilidad transversal por innovar",
    },
    {
      code: "D7.2",
      dim: "D7",
      text: "Los equipos de distintas áreas colaboran con fluidez cuando un proyecto lo requiere.",
      low: "La colaboración entre áreas es difícil, lenta o conflictiva.",
      mid: "La colaboración ocurre, pero depende de relaciones personales o presión directiva.",
      high: "Las áreas colaboran con fluidez cuando el proyecto lo necesita.",
      signal: "Colaboración interdepartamental",
    },
    {
      code: "D7.3",
      dim: "D7",
      text: "En la práctica, los departamentos comparten información de manera oportuna y trabajan de forma coordinada entre sí cuando es necesario.",
      low: "Predominan silos: poca información compartida y baja coordinación.",
      mid: "La información se comparte parcialmente o con retrasos entre áreas.",
      high: "Los departamentos comparten información oportunamente y coordinan acciones cuando hace falta.",
      signal: "Flujo de información entre áreas",
    },
    {
      code: "D7.4",
      dim: "D7",
      text: "Las diferencias o tensiones entre departamentos se gestionan de forma que no impidan avanzar iniciativas que benefician a la empresa en general.",
      low: "Las tensiones entre áreas bloquean iniciativas de valor para la empresa.",
      mid: "Las tensiones se resuelven a veces, pero siguen frenando parte de las iniciativas.",
      high: "Las tensiones se gestionan sin impedir el avance de iniciativas beneficiosas.",
      signal: "Gestión de tensiones interdepartamentales",
    },
    {
      code: "D7.5",
      dim: "D7",
      text: "Cuando surge un problema que afecta a varias áreas, los equipos se coordinan rápido sin necesidad de que lo ordene la dirección.",
      low: "Los equipos esperan instrucciones superiores para coordinar problemas transversales.",
      mid: "La coordinación ocurre, pero suele requerir intervención directiva.",
      high: "Los equipos se coordinan rápidamente ante problemas transversales sin depender siempre de la dirección.",
      signal: "Autonomía colaborativa",
    },
    {
      code: "D7.6",
      dim: "D7",
      text: "En mi empresa, cuando surgen conflictos interdepartamentales, se distingue si provienen de diferencias entre personas o de problemas en la estructura de trabajo.",
      low: "Los conflictos entre áreas se atribuyen superficialmente a personas sin analizar causas estructurales.",
      mid: "A veces se analiza el origen del conflicto, pero no de manera consistente.",
      high: "La organización diferencia si los conflictos provienen de personas o de estructura para abordarlos mejor.",
      signal: "Análisis de causas de conflictos entre áreas",
    },
    {
      code: "D8.1",
      dim: "D8",
      text: "Los líderes de mi empresa usan personalmente herramientas digitales nuevas y las recomiendan desde su propia experiencia.",
      low: "Los líderes recomiendan herramientas que no usan o muestran poca adopción personal.",
      mid: "Algunos líderes modelan uso digital, pero no es una práctica extendida.",
      high: "Los líderes usan herramientas digitales nuevas y recomiendan desde su experiencia.",
      signal: "Modelaje digital del liderazgo",
    },
    {
      code: "D8.2",
      dim: "D8",
      text: "He visto a un líder de mi empresa admitir en público que no sabía algo y aprender de ello.",
      low: "Los líderes rara vez muestran vulnerabilidad o aprendizaje público.",
      mid: "Algunos líderes admiten desconocimiento, pero no es una práctica visible.",
      high: "El liderazgo modela aprendizaje al admitir desconocimiento y aprender públicamente.",
      signal: "Humildad y aprendizaje directivo",
    },
    {
      code: "D8.3",
      dim: "D8",
      text: "Los líderes de mi empresa han cambiado de posición frente a una idea cuando les presentaron argumentos sólidos.",
      low: "Los líderes sostienen posiciones aunque existan argumentos sólidos para ajustarlas.",
      mid: "El cambio de posición ocurre, pero depende de la persona o del tema.",
      high: "Los líderes cambian de posición cuando reciben argumentos sólidos.",
      signal: "Apertura directiva a argumentos",
    },
    {
      code: "D8.4",
      dim: "D8",
      text: "El tiempo que los líderes dedican a aprender cosas nuevas es visible para el resto de la organización.",
      low: "El aprendizaje de los líderes no es visible o no se percibe como prioridad.",
      mid: "El aprendizaje directivo es visible de manera parcial o aislada.",
      high: "Los líderes hacen visible su dedicación a aprender cosas nuevas.",
      signal: "Visibilidad del aprendizaje directivo",
    },
    {
      code: "D8.5",
      dim: "D8",
      text: "En mi empresa, el liderazgo predica la innovación en el discurso y también experimenta con cosas nuevas en la práctica.",
      low: "Hay brecha entre discurso innovador y experimentación real del liderazgo.",
      mid: "El liderazgo experimenta en algunos casos, pero con coherencia parcial.",
      high: "El liderazgo acompaña el discurso innovador con experimentación práctica.",
      signal: "Coherencia entre discurso y práctica del liderazgo",
    },
    {
      code: "D8.6",
      dim: "D8",
      text: "Los directivos de mi empresa modelan con su comportamiento cotidiano los valores de apertura y aprendizaje que exigen a otros.",
      low: "Los directivos exigen apertura y aprendizaje, pero no los modelan consistentemente.",
      mid: "El modelaje directivo existe, pero de forma irregular o dependiente de personas específicas.",
      high: "Los directivos modelan cotidianamente apertura y aprendizaje.",
      signal: "Modelaje conductual de valores innovadores",
    },
  ];

  // Para una puntuación 1-5, devuelve el bucket: 'low' | 'mid' | 'high'
  function bucket(score) {
    if (score <= 2) return 'low';
    if (score === 3) return 'mid';
    return 'high';
  }

  // Devuelve el texto interpretativo para un ítem dado su score
  function interpret(code, score) {
    const it = items.find(x => x.code === code);
    if (!it) return null;
    const b = bucket(score);
    return { item: it, level: b, text: it[b], signal: it.signal };
  }

  return { items, dimTitles, bucket, interpret };
})();
